### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by felipejfc** [emqtt/emqttd#1175]
#### Environment

- OS: alpine 3.5
- Erlang/OTP: the one from https://github.com/emqtt/emq-docker
- EMQ: 2.3 beta1

#### Description

*A description of the issue*

Hi, I'm running emqtt on kubernetes using emq-docker, it's a cluster defined by the following yaml:

```
apiVersion: v1
kind: Service
metadata:
  name: emqtt
  namespace: emqtt
  labels:
    app: emqtt
spec:
  ports:
    - port: 1883
      name: mqtt
    - port: 8883
      name: mqttssl
    - port: 8080
      name: mgmt
    - port: 18083
      name: dashboard
    - port: 4369
      name: mapping
  clusterIP: None
  selector:
    app: emqtt
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: emqtt
  namespace: emqtt
spec:
  replicas: 4
  serviceName: emqtt
  template:
    metadata:
      labels: 
        app: emqtt
    spec:
      containers:
      - name: emqtt
        image: felipejfc/emqtt:v1
        ports:
          - containerPort: 1883
          - containerPort: 8883
          - containerPort: 8080
          - containerPort: 18083
          - containerPort: 4369
          - containerPort: 4370
          - containerPort: 6369
          - containerPort: 6370
          - containerPort: 6371
          - containerPort: 6372
          - containerPort: 6373
          - containerPort: 6374
          - containerPort: 6375
          - containerPort: 6376
          - containerPort: 6377
          - containerPort: 6378
        resources:
          requests:
            cpu: 1024m
            memory: 1024Mi
          limits:
            cpu: 1024m
            memory: 2048Mi
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: EMQ_CLUSTER__DISCOVERY
            value: "k8s"
          - name: EMQ_CLUSTER__K8S__APISERVER
            value: "https:\\/\\/kubernetes.default:443"
          - name: EMQ_CLUSTER__K8S__SERVICE_NAME
            value: "emqtt"
          - name: EMQ_CLUSTER__K8S__ADDRESS_TYPE
            value: "ip"
          - name: EMQ_CLUSTER__K8S__APP_NAME
            value: "emqtt"
          - name: EMQ_NODE__NAME
            value: "emqtt"
          - name: EMQ_NODE__COOKIE
            value: "secretcookieeeetfggggg"
          - name: EMQ_CLUSTER__NAME
            value: "emqcl"
          - name: EMQ_CLUSTER__AUTOHEAL
            value: "on"
          - name: EMQ_CLUSTER__AUTOCLEAN
            value: "5m"
          - name: EMQ_JOIN_CLUSTER
            value: "emqtt@emqtt-0.emqtt.emqtt.svc.cluster.local"
```

This is the memory usage graph:

![image](https://user-images.githubusercontent.com/285782/28746442-b8c9c476-7462-11e7-8f0d-998f80c9be2c.png)

```
listener on mqtt:api:127.0.0.1:8080
  acceptors       : 4
  max_clients     : 64
  current_clients : 0
  shutdown_count  : []
listener on mqtt:wss:8084
  acceptors       : 4
  max_clients     : 64
  current_clients : 0
  shutdown_count  : []
listener on mqtt:ssl:8883
  acceptors       : 32
  max_clients     : 500000
  current_clients : 0
  shutdown_count  : []
listener on mqtt:ws:8083
  acceptors       : 16
  max_clients     : 250000
  current_clients : 0
  shutdown_count  : []
listener on mqtt:tcp:0.0.0.0:1883
  acceptors       : 64
  max_clients     : 1000000
  current_clients : 4331
  shutdown_count  : [{keepalive_timeout,8982},{protocol_not_connected,3},{closed,32687},{mnesia_conflict,31},{conflict,2793},{idle_timeout,79}]
listener on mqtt:tcp:127.0.0.1:11883
  acceptors       : 16
  max_clients     : 102400
  current_clients : 0
  shutdown_count  : []
listener on dashboard:http:18083
  acceptors       : 2
  max_clients     : 512
  current_clients : 4
  shutdown_count  : []
```

```
/opt/emqttd # ./bin/emqttd_ctl broker metrics

bytes/received          : 60775407
bytes/sent              : 897437376
messages/dropped        : 7144
messages/qos0/received  : 2549
messages/qos0/sent      : 1149731
messages/qos1/received  : 0
messages/qos1/sent      : 0
messages/qos2/dropped   : 0
messages/qos2/received  : 35607
messages/qos2/sent      : 128227
messages/received       : 38156
messages/retained       : 394
messages/sent           : 1277958
packets/connack         : 111854
packets/connect         : 111889
packets/disconnect      : 74039
packets/pingreq         : 396920
packets/pingresp        : 396920
packets/puback/missed   : 0
packets/puback/received : 0
packets/puback/sent     : 0
packets/pubcomp/missed  : 93
packets/pubcomp/received: 121513
packets/pubcomp/sent    : 35606
packets/publish/received: 38156
packets/publish/sent    : 1277958
packets/pubrec/missed   : 2
packets/pubrec/received : 121789
packets/pubrec/sent     : 35607
packets/pubrel/missed   : 1
packets/pubrel/received : 35606
packets/pubrel/sent     : 121789
packets/received        : 1046765
packets/sent            : 2126506
packets/suback          : 146251
packets/subscribe       : 146332
packets/unsuback        : 521
packets/unsubscribe     : 521
```
```
/opt/emqttd # ./bin/emqttd_ctl broker stats

clients/count       : 4422
clients/max         : 4449
retained/count      : 396
retained/max        : 396
routes/count        : 136622
routes/max          : 136622
sessions/count      : 14927
sessions/max        : 14927
subscribers/count   : 35390
subscribers/max     : 35390
subscriptions/count : 35393
subscriptions/max   : 35393
topics/count        : 0
topics/max          : 0
```
```
/opt/emqttd # ./bin/emqttd_ctl vm memory
memory/total            : 402492944
memory/processes        : 137168280
memory/processes_used   : 136672608
memory/system           : 265324664
memory/atom             : 1115337
memory/atom_used        : 1084490
memory/binary           : 59822848
memory/code             : 27690467
memory/ets              : 141919312
/opt/emqttd # ./bin/emqttd_ctl vm
cpu/load1               : 3.93
cpu/load5               : 3.35
cpu/load15              : 3.21
memory/total            : 398836408
memory/processes        : 133345400
memory/processes_used   : 132792560
memory/system           : 265491008
memory/atom             : 1115337
memory/atom_used        : 1084598
memory/binary           : 59789416
memory/code             : 27690467
memory/ets              : 142139272
process/limit           : 2097152
process/count           : 19788
io/max_fds              : 1048576
io/active_fds           : 1
ports/count           : 4449
ports/limit           : 1048576
```

Our use case is:

We want to use emqtt as a chat service for like 10K concurrent connected users and some hundreds of thousands of unique users daily, always with the same clientid(one per user), with very few offline/retained messages...

Regards
