### ISSUE TITLE
use auth_http and connecting make the server crashed

### ISSUE THREAD

**Issue by hello2dj** [emqtt/emqttd#1427]
#### Environment

- OS: Ubuntu 16.04.2 LTS
- Erlang/OTP: how to see this ...
- EMQ: emqttd-docker-v2.3.1

#### Description

*A description of the issue*
i use auth_http plugins and the compose file is
```
version: '3'

services:
    emqtt-server:
        #build: .
        image: "emqttd-docker-v2.3.1"
        container_name: emqtt-server
        restart: always
        ports:
            - "8883:8883"
            - "1883:1883"
            - "18083:18083"
        environment:
            - EMQ_LOADED_PLUGINS="emq_auth_http,emq_recon,emq_modules,emq_retainer,emq_dashboard"
            - EMQ_AUTH__HTTP__AUTH_REQ="http:\/\/172.25.100.3:7001\/mqtt\/auth"
            - EMQ_AUTH__HTTP__AUTH_REQ__METHOD=post
            - EMQ_AUTH__HTTP__SUPER_REQ="http:\/\/172.25.100.3:7001\/mqtt\/auth"
            - EMQ_AUTH__USER__1__USERNAME=admin
            - EMQ_AUTH__USER__1__PASSWORD=public
        volumes:
            - /home/dj/etc/certs:/opt/emqttd/etc/certs:ro
        user: root
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "5"
```
but when i connect to the server, it says crash, and the crash report is 
```
CRASH REPORT Process <0.1726.0> with 0 neighbours crashed with reason: no function clause matching httpc_handler:socket_type({request,#Ref<0.0.1.2007>,<0.1722.0>,0,'"http',{"172.25.100.3",7001},"/mqtt/auth\"",[],post,{http_request_h,...},...}) line 1642
```
who can help me ?

**Comment by turtleDeng** [comment]
@hello2dj 
Please add an '\\' escape character before '/'

**Comment by hello2dj** [comment]
/home/dj/etc/certs:/opt/emqttd/etc/certs:ro you mean that this need to be escaped ?

**Comment by hello2dj** [comment]
you mean this  http:\\/\\/172.25.100.3:7001\\/mqtt\\/auth?

**Comment by hello2dj** [comment]
http:\\/\\/172.25.100.3:7001\\/mqtt\\/auth ?

**Comment by hello2dj** [comment]
@turtleDeng  sorry I don't get you.  you mean this  "http:\\/\\/172.25.100.3:7001\\/mqtt\\/auth?"

**Comment by hello2dj** [comment]
I  get this 
auth.http.auth_req="http:\\/\\/172.25.100.3:7001\\/mqtt\\/auth"
emqtt-server    | sed: bad option in substitution expression
emqtt-server    | listener.ssl.external.max_clients=500000
emqtt-server    | node.max_ports=1048576
emqtt-server    | listener.tcp.external.acceptors=64
emqtt-server    | log.console=console
emqtt-server    | listener.ws.external.max_clients=250000
emqtt-server    | name=71b55963c6fc
emqtt-server    | auth.http.super_req="http:\\/\\/172.25.100.3:7001\\/mqtt\\/auth"
emqtt-server    | sed: bad option in substitution expression
emqtt-server    | auth.http.auth_req.method=post

**Comment by hello2dj** [comment]
i use // but github discard one

**Comment by turtleDeng** [comment]
```
version: '3'

services:
    emqtt-server:
        #build: .
        image: "emqttd-docker-v2.3.1"
        container_name: emqtt-server
        restart: always
        ports:
            - "8883:8883"
            - "1883:1883"
            - "18083:18083"
        environment:
            - EMQ_LOADED_PLUGINS="emq_auth_http,emq_recon,emq_modules,emq_retainer,emq_dashboard"
            - EMQ_AUTH__HTTP__AUTH_REQ="http:\\/\\/172.25.100.3:7001\\/mqtt\\/auth"
            - EMQ_AUTH__HTTP__AUTH_REQ__METHOD=post
            - EMQ_AUTH__HTTP__SUPER_REQ="http:\\/\\/172.25.100.3:7001\\/mqtt\\/auth"
            - EMQ_AUTH__USER__1__USERNAME=admin
            - EMQ_AUTH__USER__1__PASSWORD=public
        volumes:
            - /home/dj/etc/certs:/opt/emqttd/etc/certs:ro
        user: root
        logging:
            driver: "json-file"
            options:
                max-size: "200m"
                max-file: "5"
```
