### ISSUE TITLE
EMQ Can't work with istio in k8s

### ISSUE THREAD

**Issue by eastpav** [emqtt/emqttd#1621]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

**Comment by silencecorner** [comment]
**testing in istio 1.0 in my k8s cluster**

#### emqtt.rbac.yaml
```bash
kubectl create namespace emqtt
kubectl apply -f emqtt.rbac.yaml
```
```yaml
# emqtt.rbac.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqtt
  namespace: emqtt
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: emqtt
  namespace: emqtt
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: emqtt
  namespace: emqtt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: emqtt
subjects:
- kind: ServiceAccount
  name: emqtt
  namespace: emqtt
```
#### emqtt-deployment.yaml
```bash
kubectl apply -f emqtt-deployment.yaml
```
```yaml
# emqtt-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: emqtt
  namespace: emqtt
  labels:
    app: emqtt
spec:
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
      nodePort: 1883
    - port: 8883
      name: mqttssl
    - port: 8080
      name: mgmt
    - port: 18083
      nodePort: 18083
      name: dashboard
    - port: 4369
      name: mapping
  type: LoadBalancer
  selector:
    app: emqtt
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: emqtt
  namespace: emqtt
spec:
  replicas: 3
  serviceName: emqtt
  template:
    metadata:
      labels:
        app: emqtt
    spec:
      serviceAccountName: emqtt
      containers:
      - name: emqtt
        image: emqx/emqx:v3.0-rc.5
        ports:
          - containerPort: 1883
          - containerPort: 8883
          - containerPort: 8080
          - containerPort: 18083
          - containerPort: 4369
          - containerPort: 4370
          - containerPort: 6369
          - containerPort: 6370
          - containerPort: 6371
          - containerPort: 6372
          - containerPort: 6373
          - containerPort: 6374
          - containerPort: 6375
          - containerPort: 6376
          - containerPort: 6377
          - containerPort: 6378
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: EMQX_NAME
            value: "emqtt"
          - name: EMQX_CLUSTER__DISCOVERY
            value: "k8s"
          - name: EMQX_CLUSTER__K8S__APISERVER
            value: "https://kubernetes.default:443"
          - name: EMQX_CLUSTER__K8S__NAMESPACE
            value: "emqtt"
          - name: EMQX_CLUSTER__K8S__SERVICE_NAME
            value: "emqtt"
          - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
            value: "ip"
          - name: EMQX_CLUSTER__K8S__APP_NAME
            value: "emqtt"
          - name: EMQX_NODE__COOKIE
            value: "secretcookieeeetfggggg"
          - name: EMQX_CLUSTER__NAME
            value: "emqcl"
          - name: EMQX_CLUSTER__AUTOHEAL
            value: "on"
          - name: EMQX_CLUSTER__AUTOCLEAN
            value: "5m"
          - name: TZ
            value: Asia/Shanghai
        tty: true
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
```
#### emqtt-serviceentry.yaml
```bash
istioctl create -f emqtt-serviceentry.yaml
```
```yaml
# emqtt-serviceentry.yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: emqtt
spec:
  hosts:
  - emqtt.emqtt.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - number: 1883
    name: tcp
    protocol: TCP
  resolution: DNS
```
hope to help you!
