### ISSUE TITLE
Docker DNS discovery not working?

### ISSUE THREAD

**Issue by vicary** [emqtt/emqttd#1752]
#### Environment

- OS: Docker
- Erlang/OTP: R20/9.1.5
- EMQ: 2.3.11

#### Description

I tried to build a cluster with DNS discovery but the nodes didn’t form a cluster themselves.

This is the stack YAML I was using.

```YAML
version "3"

services:
  emqcl:
    image: emqttd
    ports:
      - 1883:1883
      - 8083:8083
      - 18083:18083
    environment:
      - EMQ_CLUSTER__DISCOVERY=dns
      - EMQ_CLUSTER__DNS__NAME=emqcl
      - EMQ_CLUSTER__DNS__APP=emqcl
    networks:
      - emqtt
    deploy:
      replicas: 3
      restart_policy:
        condition: always
networks:
  emqtt:
    driver: overlay
```

The service log keeps warning for "emqcl" is not a FQDN, not sure if that’s critical because overlay networks does not allow "dots" in their names.
