### ISSUE TITLE
unable to connect paho java lib to emqtt (0.16.0)

### ISSUE THREAD

**Issue by sylvek** [emqtt/emqttd#465]
Hi,

I do some tests to connect a java client to my emqtt server.

server side (ansible script)

```
- apt: update_cache=yes
      - apt: name=wget state=present
      - apt: name=unzip state=present
      - get_url: url=http://emqtt.io/downloads/ubuntu dest=/tmp/emqttd.tar.gz
      - shell: tar -xf /tmp/emqttd.tar.gz -C /opt
      - shell: ./bin/emqttd start
        args:
          chdir: /opt/emqttd
```

client side (java)

```
final MqttClient client = new MqttClient(
                "tcp://192.168.33.10:1883", //URI
                "testclientid3", //ClientId
                new MemoryPersistence()); //Persistence
...
MqttConnectOptions options = new MqttConnectOptions();
        options.setMqttVersion(MqttConnectOptions.MQTT_VERSION_3_1_1);
        client.connect(options);
        client.subscribe("/sensors/#");
```

with… /opt/emqttd/etc/clients.config

```
...
testclientid3 192.168.33.1/24
```

this same code works properly with mosquitto.

and with emqtt i trace this on connection.

```
11:28:00.966 [error] Client testclientid3 is Down: {{badmatch,{error,downtime}},[{emqttd_mod_kafka_presence,client_connected,3,[{file,"src/emqttd_mod_kafka_presence.erl"},{line,67}]},{lists,foreach,2,[{file,"lists.erl"},{line,1337}]},{emqttd_protocol,handle,2,[{file,"src/emqttd_protocol.erl"},{line,171}]},{emqttd_client,process_received_bytes,2,[{file,"src/emqttd_client.erl"},{line,195}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
```
